---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv004"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
          path: "/mnt/ext/wordpress-mysql"
---
