---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "wordpress"
  name: "pv004"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
---

