---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "jenkins"
  name: "pv003"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "50Gi"
---

