---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "wikijs"
  name: "pv006"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
---
