---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "apache"
  name: "pv001"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "50Gi"
---

