---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv001"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "50Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ext/apache"
---
